name:                MajangPoint
version:             0.1.0.0
github:              "githubuser/MajangPoint"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MajangPoint#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -w
  dependencies:
  - base >= 4.7 && < 5
  - sort
  - attoparsec
  - text
  - bytestring
  - mtl
  - transformers

executables:
  MajangPoint-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -w
    dependencies:
    - MajangPoint

tests:
  MajangPoint-tasty:
    main: Tasty.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MajangPoint
    - tasty
    - tasty-hunit
